# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/a08f8d51631b7127ddac3d2c65537db429d0f1d0/schema/compose-spec.json

services:
    empty-mod-devcontainer:
        container_name: empty-mod-devcontainer
        image: ${IMAGE_REGISTRY:-ghcr.io/imesense}/mcforge1.12.2-empty-mod-devcontainer:${IMAGE_TAG:-latest}
        platform: linux/amd64

        user: minecraft
        working_dir: /src
        volumes:
            - ${VOLUME_SOURCES:-..}:/src:delegated
            - ${VOLUME_GRADLE:-../.gradle}:/gradle:delegated
        networks:
            - empty-mod-devcontainer
        command:
            - "tail"
            - "-f"
            - "/dev/null"

networks:
    empty-mod-devcontainer:
        name: empty-mod-devcontainer
        driver: bridge
